// Auto-generated from fogio-org/vscode-jetbrains-file-icon-theme light + dark themes.
// Do not hand-edit; regenerate from /tmp/jb-icons if upstream updates.

interface Theme { ICON_PATHS: Record<string, string>; BY_EXT: Record<string, string>; BY_NAME: Record<string, string>; DEFAULT: string; }

const DARK: Theme = {
  "ICON_PATHS": {
    "file_text": "/icons/jb/file/text_dark.svg",
    "file_kotlin": "/icons/jb/file/kotlin_dark.svg",
    "file_ignored": "/icons/jb/file/ignored_dark.svg",
    "file_css": "/icons/jb/file/css.svg",
    "file_erb": "/icons/jb/file/erbFile_dark.svg",
    "file_scss": "/icons/jb/file/scss.svg",
    "file_json": "/icons/jb/file/json_dark.svg",
    "file_html": "/icons/jb/file/html_dark.svg",
    "file_react": "/icons/jb/file/react_dark.svg",
    "file_ruby": "/icons/jb/file/ruby_dark.svg",
    "file_rake": "/icons/jb/file/rakeTask_dark.svg",
    "file_gemfile": "/icons/jb/file/rubyGems_dark.svg",
    "file_less": "/icons/jb/file/less_dark.svg",
    "file_javascript": "/icons/jb/file/javaScript_dark.svg",
    "file_typescript": "/icons/jb/file/typeScript_dark.svg",
    "file_csv": "/icons/jb/file/csv_dark.svg",
    "file_vue": "/icons/jb/file/vueJs.svg",
    "file_editorconfig": "/icons/jb/file/editorConfig_dark.svg",
    "file_image": "/icons/jb/file/image_dark.svg",
    "file_font": "/icons/jb/file/font_dark.svg",
    "file_yaml": "/icons/jb/file/yaml_dark.svg",
    "file_java": "/icons/jb/file/java_dark.svg",
    "file_xml": "/icons/jb/file/xml_dark.svg",
    "file_sql": "/icons/jb/file/sql_dark.svg",
    "file_slim": "/icons/jb/file/slim_dark.svg",
    "file_sln": "/icons/jb/file/solution_dark.svg",
    "file_yarn": "/icons/jb/file/yarn.svg",
    "file_markdown": "/icons/jb/file/markdown_dark.svg",
    "file_gitignore": "/icons/jb/file/gitignore.svg",
    "file_gleam": "/icons/jb/file/gleam_dark.svg",
    "file_properties": "/icons/jb/file/properties_dark.svg",
    "file_shell": "/icons/jb/file/shell_dark.svg",
    "file_h": "/icons/jb/file/h_dark.svg",
    "file_c": "/icons/jb/file/c_dark.svg",
    "file_cpp": "/icons/jb/file/cpp_dark.svg",
    "file_cu": "/icons/jb/file/cu_dark.svg",
    "file_cuh": "/icons/jb/file/cuh_dark.svg",
    "file_scala": "/icons/jb/file/scala_dark.svg",
    "file_archive": "/icons/jb/file/archive_dark.svg",
    "file_toml": "/icons/jb/file/toml_dark.svg",
    "file_python": "/icons/jb/file/python_dark.svg",
    "file_python_tests": "/icons/jb/file/pythonTests_dark.svg",
    "file_python_console": "/icons/jb/file/pythonConsole_dark.svg",
    "file_terraform": "/icons/jb/file/terraform_dark.svg",
    "file_go": "/icons/jb/file/go_dark.svg",
    "file_gomod": "/icons/jb/file/goMod_dark.svg",
    "file_gosum": "/icons/jb/file/goSum_dark.svg",
    "file_gowork": "/icons/jb/file/goWork_dark.svg",
    "file_http": "/icons/jb/file/http_dark.svg",
    "file_dart": "/icons/jb/file/dart_dark.svg",
    "file_docker": "/icons/jb/file/docker_dark.svg",
    "file_actionscript": "/icons/jb/file/actionScript_dark.svg",
    "file_php": "/icons/jb/file/php_dark.svg",
    "file_makefile": "/icons/jb/file/makefile_dark.svg",
    "file_config": "/icons/jb/file/config_dark.svg",
    "file_any": "/icons/jb/file/anyType_dark.svg",
    "file_svelte": "/icons/jb/file/svelte.svg",
    "file_rust": "/icons/jb/file/rustFile_dark.svg",
    "file_cargo": "/icons/jb/file/cargo_dark.svg",
    "file_cargolock": "/icons/jb/file/cargoLock_dark.svg",
    "file_cmake": "/icons/jb/file/CMake_dark.svg",
    "file_pnpm": "/icons/jb/file/pnpm_dark.svg",
    "file_tailwind": "/icons/jb/file/tailwind.svg",
    "file_vite": "/icons/jb/file/vite_dark.svg",
    "file_postcss": "/icons/jb/file/postcss.svg",
    "file_angular": "/icons/jb/file/angularJS.svg",
    "file_eslint": "/icons/jb/file/eslint.svg",
    "file_cs": "/icons/jb/file/cs_dark.svg",
    "file_cshtml": "/icons/jb/file/cshtml_dark.svg",
    "file_csproj": "/icons/jb/file/csproj_dark.svg",
    "file_elixir": "/icons/jb/file/elixir_dark.svg",
    "file_beam": "/icons/jb/file/beam.svg",
    "file_embedded_elixir": "/icons/jb/file/eex_dark.svg",
    "file_swift": "/icons/jb/file/swift.svg",
    "file_clojure": "/icons/jb/file/clojure.svg",
    "file_ml": "/icons/jb/file/ml.svg",
    "file_mli": "/icons/jb/file/mli.svg",
    "file_dune": "/icons/jb/file/dune.svg",
    "file_opam": "/icons/jb/file/opam.svg",
    "file_protobuf": "/icons/jb/file/protoFile_dark.svg",
    "file_hcl": "/icons/jb/file/hcl_dark.svg",
    "file_rego": "/icons/jb/file/rego.svg",
    "file_application": "/icons/jb/file/application_dark.svg",
    "file_jupyter": "/icons/jb/file/jupyter.svg",
    "file_mdx": "/icons/jb/file/mdx.svg",
    "file_erlang": "/icons/jb/file/erlang.svg",
    "file_lua": "/icons/jb/file/lua.svg",
    "file_haskell": "/icons/jb/file/haskell.svg",
    "file_graphql": "/icons/jb/file/graphql.svg",
    "file_buildprops": "/icons/jb/file/projectProperties_dark.svg",
    "file_test_ts": "/icons/jb/file/tsTest_dark.svg",
    "file_test_tsx": "/icons/jb/file/tsxTest_dark.svg",
    "file_test_js": "/icons/jb/file/jsTest_dark.svg",
    "file_test_jsx": "/icons/jb/file/jsxTest_dark.svg",
    "file_jsx": "/icons/jb/file/jsx_dark.svg",
    "file_db": "/icons/jb/file/dbms_dark.svg",
    "file_lock": "/icons/jb/file/lock_dark.svg",
    "file_ino": "/icons/jb/file/ino_dark.svg",
    "file_pdf": "/icons/jb/file/pdf.svg",
    "file_jinja": "/icons/jb/file/jinja_dark.svg",
    "file_go_template": "/icons/jb/file/goTemplate_dark.svg",
    "file_go_run": "/icons/jb/file/goRunApplication_dark.svg",
    "file_go_test": "/icons/jb/file/goTest_dark.svg",
    "file_jenkins": "/icons/jb/file/jenkins.svg",
    "file_groovy": "/icons/jb/file/groovy_dark.svg",
    "file_schema": "/icons/jb/file/schema_dark.svg"
  },
  "BY_EXT": {
    "ml": "file_ml",
    "mli": "file_mli",
    "opam": "file_opam",
    "css": "file_css",
    "dart": "file_dart",
    "erb": "file_erb",
    "scss": "file_scss",
    "sass": "file_scss",
    "kt": "file_kotlin",
    "json": "file_json",
    "jsonc": "file_json",
    "json5": "file_json",
    "html": "file_html",
    "jsx": "file_jsx",
    "tsx": "file_react",
    "rake": "file_rake",
    "rb": "file_ruby",
    "less": "file_less",
    "js": "file_javascript",
    "cjs": "file_javascript",
    "mjs": "file_javascript",
    "ts": "file_typescript",
    "cts": "file_typescript",
    "mts": "file_typescript",
    "csv": "file_csv",
    "xlsx": "file_csv",
    "xls": "file_csv",
    "vue": "file_vue",
    "png": "file_image",
    "webp": "file_image",
    "jpg": "file_image",
    "jpeg": "file_image",
    "gif": "file_image",
    "gleam": "file_gleam",
    "ico": "file_image",
    "svg": "file_image",
    "ttf": "file_font",
    "woff": "file_font",
    "oft": "file_font",
    "eot": "file_font",
    "yaml": "file_yaml",
    "yml": "file_yaml",
    "java": "file_java",
    "xml": "file_xml",
    "sql": "file_sql",
    "md": "file_markdown",
    "properties": "file_properties",
    "sh": "file_shell",
    "zsh": "file_shell",
    "bash": "file_shell",
    "bat": "file_shell",
    "ps1": "file_shell",
    "h": "file_h",
    "hh": "file_h",
    "hpp": "file_h",
    "hxx": "file_h",
    "c": "file_c",
    "cc": "file_cpp",
    "cpp": "file_cpp",
    "cxx": "file_cpp",
    "ccm": "file_cpp",
    "cxxm": "file_cpp",
    "cppm": "file_cpp",
    "c++m": "file_cpp",
    "ixx": "file_cpp",
    "cu": "file_cu",
    "cuh": "file_cuh",
    "scala": "file_scala",
    "gz": "file_archive",
    "zip": "file_archive",
    "rar": "file_archive",
    "7z": "file_archive",
    "tar": "file_archive",
    "toml": "file_toml",
    "py": "file_python",
    "pyi": "file_python",
    "pyc": "file_python",
    "tf": "file_terraform",
    "go": "file_go",
    "http": "file_http",
    "rest": "file_http",
    "as": "file_actionscript",
    "php": "file_php",
    "cfg": "file_config",
    "conf": "file_config",
    "config": "file_config",
    "cnf": "file_config",
    "svelte": "file_svelte",
    "slim": "file_slim",
    "sln": "file_sln",
    "rs": "file_rust",
    "cs": "file_cs",
    "cshtml": "file_cshtml",
    "csproj": "file_csproj",
    "ex": "file_elixir",
    "exs": "file_elixir",
    "eex": "file_embedded_elixir",
    "heex": "file_embedded_elixir",
    "leex": "file_embedded_elixir",
    "beam": "file_beam",
    "dockerfile": "file_docker",
    "swift": "file_swift",
    "cljc": "file_clojure",
    "cljs": "file_clojure",
    "clj": "file_clojure",
    "edn": "file_clojure",
    "proto": "file_protobuf",
    "hcl": "file_hcl",
    "rego": "file_rego",
    "exe": "file_application",
    "ipynb": "file_jupyter",
    "mdx": "file_mdx",
    "erl": "file_erlang",
    "lua": "file_lua",
    "hs": "file_haskell",
    "graphql": "file_graphql",
    "gql": "file_graphql",
    "test.ts": "file_test_ts",
    "test.tsx": "file_test_tsx",
    "test.jsx": "file_test_jsx",
    "test.js": "file_test_js",
    "db": "file_db",
    "sqlite": "file_db",
    "sqlite3": "file_db",
    "db3": "file_db",
    "accdb": "file_db",
    "mdb": "file_db",
    "dbf": "file_db",
    "ndf": "file_db",
    "ibd": "file_db",
    "frm": "file_db",
    "ora": "file_db",
    "lock": "file_lock",
    "ino": "file_ino",
    "jinja": "file_jinja",
    "jinja2": "file_jinja",
    "j2": "file_jinja",
    "html.j2": "file_jinja",
    "razor": "file_cshtml",
    "cmake": "file_cmake",
    "pdf": "file_pdf",
    "gohtml": "file_go_template",
    "gotmpl": "file_go_template",
    "groovy": "file_groovy",
    "bpmn": "file_schema",
    "arb": "file_json"
  },
  "BY_NAME": {
    "dune": "file_dune",
    "dune-projecT": "file_dune",
    ".gitignore": "file_gitignore",
    ".gitattributes": "file_gitignore",
    ".gitmodules": "file_gitignore",
    ".gitkeep": "file_gitignore",
    ".editorconfig": "file_editorconfig",
    ".yarnrc": "file_yarn",
    "yarn.lock": "file_yarn",
    "README": "file_markdown",
    ".dockerignore": "file_ignored",
    "Dockerfile": "file_docker",
    "Dockerfile.dev": "file_docker",
    "Dockerfile.test": "file_docker",
    "Dockerfile.staging": "file_docker",
    "Dockerfile.prod": "file_docker",
    "Dockerfile.production": "file_docker",
    "Gemfile": "file_gemfile",
    "Gemfile.lock": "file_gemfile",
    "Makefile": "file_makefile",
    ".env": "file_text",
    ".env.local": "file_text",
    ".env.test": "file_text",
    ".env.example": "file_text",
    ".env.development": "file_text",
    ".env.production": "file_text",
    ".env.test.local": "file_text",
    ".env.development.local": "file_text",
    ".env.production.local": "file_text",
    ".env.db": "file_text",
    "Cargo.toml": "file_cargo",
    "rust-toolchain.toml": "file_cargo",
    "Cargo.lock": "file_cargolock",
    "CMakeLists.txt": "file_cmake",
    "CMakeCache.txt": "file_config",
    "pnpm-lock.yaml": "file_pnpm",
    "pnpm-workspace.yaml": "file_pnpm",
    "tailwind.config.js": "file_tailwind",
    "tailwind.config.cjs": "file_tailwind",
    "tailwind.config.ts": "file_tailwind",
    "vite.config.js": "file_vite",
    "vite.config.cjs": "file_vite",
    "vite.config.ts": "file_vite",
    "postcss.config.js": "file_postcss",
    "postcss.config.cjs": "file_postcss",
    "postcss.config.ts": "file_postcss",
    "angular.json": "file_angular",
    ".eslintrc": "file_eslint",
    ".eslintrc.cjs": "file_eslint",
    ".eslintrc.js": "file_eslint",
    ".eslintrc.ts": "file_eslint",
    ".eslintrc.json": "file_eslint",
    ".eslintrc.yml": "file_eslint",
    ".eslintrc.yaml": "file_eslint",
    ".eslintignore": "file_eslint",
    "go.mod": "file_gomod",
    "go.sum": "file_gosum",
    "go.work": "file_gowork",
    "Directory.Build.props": "file_buildprops",
    "main.go": "file_go_run",
    "conftest.py": "file_python_tests",
    "__init__.py": "file_python_console",
    "Jenkinsfile": "file_jenkins"
  },
  "DEFAULT": "file_text"
};

const LIGHT: Theme = {
  "ICON_PATHS": {
    "file_text_light": "/icons/jb/file/text.svg",
    "file_kotlin_light": "/icons/jb/file/kotlin.svg",
    "file_ignored_light": "/icons/jb/file/ignored.svg",
    "file_css_light": "/icons/jb/file/css.svg",
    "file_erb_light": "/icons/jb/file/erbFile.svg",
    "file_scss_light": "/icons/jb/file/scss.svg",
    "file_json_light": "/icons/jb/file/json.svg",
    "file_html_light": "/icons/jb/file/html.svg",
    "file_react_light": "/icons/jb/file/react.svg",
    "file_ruby_light": "/icons/jb/file/ruby.svg",
    "file_rake_light": "/icons/jb/file/rakeTask.svg",
    "file_gemfile_light": "/icons/jb/file/rubyGems.svg",
    "file_less_light": "/icons/jb/file/less.svg",
    "file_javascript_light": "/icons/jb/file/javaScript.svg",
    "file_typescript_light": "/icons/jb/file/typeScript.svg",
    "file_csv_light": "/icons/jb/file/csv.svg",
    "file_vue_light": "/icons/jb/file/vueJs.svg",
    "file_editorconfig_light": "/icons/jb/file/editorConfig.svg",
    "file_image_light": "/icons/jb/file/image.svg",
    "file_font_light": "/icons/jb/file/font.svg",
    "file_yaml_light": "/icons/jb/file/yaml.svg",
    "file_java_light": "/icons/jb/file/java.svg",
    "file_xml_light": "/icons/jb/file/xml.svg",
    "file_sql_light": "/icons/jb/file/sql.svg",
    "file_slim_light": "/icons/jb/file/slim.svg",
    "file_sln_light": "/icons/jb/file/solution.svg",
    "file_yarn_light": "/icons/jb/file/yarn.svg",
    "file_markdown_light": "/icons/jb/file/markdown.svg",
    "file_gitignore_light": "/icons/jb/file/gitignore.svg",
    "file_gleam_light": "/icons/jb/file/gleam.svg",
    "file_properties_light": "/icons/jb/file/properties.svg",
    "file_shell_light": "/icons/jb/file/shell.svg",
    "file_h_light": "/icons/jb/file/h.svg",
    "file_c_light": "/icons/jb/file/c.svg",
    "file_cpp_light": "/icons/jb/file/cpp.svg",
    "file_cu_light": "/icons/jb/file/cu.svg",
    "file_cuh_light": "/icons/jb/file/cuh.svg",
    "file_scala_light": "/icons/jb/file/scala.svg",
    "file_archive_light": "/icons/jb/file/archive.svg",
    "file_toml_light": "/icons/jb/file/toml.svg",
    "file_python_light": "/icons/jb/file/python.svg",
    "file_python_tests_light": "/icons/jb/file/pythonTests.svg",
    "file_python_console_light": "/icons/jb/file/pythonConsole.svg",
    "file_terraform_light": "/icons/jb/file/terraform.svg",
    "file_go_light": "/icons/jb/file/go.svg",
    "file_gomod_light": "/icons/jb/file/goMod.svg",
    "file_gosum_light": "/icons/jb/file/goSum.svg",
    "file_gowork_light": "/icons/jb/file/goWork.svg",
    "file_http_light": "/icons/jb/file/http.svg",
    "file_dart_light": "/icons/jb/file/dart.svg",
    "file_docker_light": "/icons/jb/file/docker.svg",
    "file_actionscript_light": "/icons/jb/file/actionScript.svg",
    "file_php_light": "/icons/jb/file/php.svg",
    "file_makefile_light": "/icons/jb/file/makefile.svg",
    "file_config_light": "/icons/jb/file/config.svg",
    "file_any_light": "/icons/jb/file/anyType.svg",
    "file_svelte_light": "/icons/jb/file/svelte.svg",
    "file_rust_light": "/icons/jb/file/rustFile.svg",
    "file_cargo_light": "/icons/jb/file/cargo.svg",
    "file_cargolock_light": "/icons/jb/file/cargoLock.svg",
    "file_cmake_light": "/icons/jb/file/CMake.svg",
    "file_pnpm_light": "/icons/jb/file/pnpm.svg",
    "file_tailwind_light": "/icons/jb/file/tailwind.svg",
    "file_vite_light": "/icons/jb/file/vite.svg",
    "file_postcss_light": "/icons/jb/file/postcss.svg",
    "file_angular_light": "/icons/jb/file/angularJS.svg",
    "file_eslint_light": "/icons/jb/file/eslint.svg",
    "file_cs_light": "/icons/jb/file/cs.svg",
    "file_cshtml_light": "/icons/jb/file/cshtml.svg",
    "file_csproj_light": "/icons/jb/file/csproj.svg",
    "file_elixir_light": "/icons/jb/file/elixir.svg",
    "file_beam_light": "/icons/jb/file/beam.svg",
    "file_embedded_elixir_light": "/icons/jb/file/eex.svg",
    "file_swift_light": "/icons/jb/file/swift.svg",
    "file_clojure_light": "/icons/jb/file/clojure.svg",
    "file_ml_light": "/icons/jb/file/ml.svg",
    "file_mli_light": "/icons/jb/file/mli.svg",
    "file_dune_light": "/icons/jb/file/dune.svg",
    "file_opam_light": "/icons/jb/file/opam.svg",
    "file_protobuf_light": "/icons/jb/file/protoFile.svg",
    "file_hcl_light": "/icons/jb/file/hcl_light.svg",
    "file_rego_light": "/icons/jb/file/rego.svg",
    "file_application_light": "/icons/jb/file/application.svg",
    "file_jupyter_light": "/icons/jb/file/jupyter.svg",
    "file_mdx_light": "/icons/jb/file/mdx.svg",
    "file_erlang_light": "/icons/jb/file/erlang.svg",
    "file_lua_light": "/icons/jb/file/lua.svg",
    "file_haskell_light": "/icons/jb/file/haskell.svg",
    "file_graphql_light": "/icons/jb/file/graphql.svg",
    "file_buildprops_light": "/icons/jb/file/projectProperties.svg",
    "file_test_ts_light": "/icons/jb/file/tsTest.svg",
    "file_test_tsx_light": "/icons/jb/file/tsxTest.svg",
    "file_test_js_light": "/icons/jb/file/jsTest.svg",
    "file_test_jsx_light": "/icons/jb/file/jsxTest.svg",
    "file_jsx_light": "/icons/jb/file/jsx.svg",
    "file_db_light": "/icons/jb/file/dbms.svg",
    "file_lock_light": "/icons/jb/file/lock.svg",
    "file_ino_light": "/icons/jb/file/ino.svg",
    "file_pdf_light": "/icons/jb/file/pdf.svg",
    "file_go_template_light": "/icons/jb/file/goTemplate.svg",
    "file_go_run_light": "/icons/jb/file/goRunApplication.svg",
    "file_go_test_light": "/icons/jb/file/goTest.svg",
    "file_jenkins": "/icons/jb/file/jenkins.svg",
    "file_groovy_light": "/icons/jb/file/groovy.svg",
    "file_schema": "/icons/jb/file/schema.svg"
  },
  "BY_EXT": {
    "ml": "file_ml_light",
    "mli": "file_mli_light",
    "opam": "file_opam_light",
    "dart": "file_dart_light",
    "css": "file_css_light",
    "scss": "file_scss_light",
    "erb": "file_erb_light",
    "sass": "file_scss_light",
    "kt": "file_kotlin_light",
    "json": "file_json_light",
    "jsonc": "file_json_light",
    "json5": "file_json_light",
    "html": "file_html_light",
    "jsx": "file_jsx_light",
    "tsx": "file_react_light",
    "rake": "file_rake_light",
    "rb": "file_ruby_light",
    "less": "file_less_light",
    "js": "file_javascript_light",
    "cjs": "file_javascript_light",
    "mjs": "file_javascript_light",
    "ts": "file_typescript_light",
    "cts": "file_typescript_light",
    "mts": "file_typescript_light",
    "csv": "file_csv_light",
    "xlsx": "file_csv_light",
    "xls": "file_csv_light",
    "vue": "file_vue_light",
    "png": "file_image_light",
    "webp": "file_image_light",
    "jpg": "file_image_light",
    "jpeg": "file_image_light",
    "gif": "file_image_light",
    "gleam": "file_gleam_light",
    "ico": "file_image_light",
    "svg": "file_image_light",
    "ttf": "file_font_light",
    "woff": "file_font_light",
    "oft": "file_font_light",
    "eot": "file_font_light",
    "yaml": "file_yaml_light",
    "yml": "file_yaml_light",
    "java": "file_java_light",
    "xml": "file_xml_light",
    "sql": "file_sql_light",
    "md": "file_markdown_light",
    "properties": "file_properties_light",
    "sh": "file_shell_light",
    "zsh": "file_shell_light",
    "bash": "file_shell_light",
    "bat": "file_shell_light",
    "ps1": "file_shell_light",
    "h": "file_h_light",
    "hh": "file_h_light",
    "hpp": "file_h_light",
    "hxx": "file_h_light",
    "c": "file_c_light",
    "cc": "file_cpp_light",
    "cpp": "file_cpp_light",
    "cxx": "file_cpp_light",
    "ccm": "file_cpp_light",
    "cxxm": "file_cpp_light",
    "cppm": "file_cpp_light",
    "c++m": "file_cpp_light",
    "ixx": "file_cpp_light",
    "cu": "file_cu_light",
    "cuh": "file_cuh_light",
    "scala": "file_scala_light",
    "gz": "file_archive_light",
    "zip": "file_archive_light",
    "rar": "file_archive_light",
    "7z": "file_archive_light",
    "tar": "file_archive_light",
    "toml": "file_toml_light",
    "py": "file_python_light",
    "pyi": "file_python_light",
    "pyc": "file_python_light",
    "tf": "file_terraform_light",
    "go": "file_go_light",
    "http": "file_http_light",
    "rest": "file_http_light",
    "as": "file_actionscript_light",
    "php": "file_php_light",
    "cfg": "file_config_light",
    "conf": "file_config_light",
    "config": "file_config_light",
    "cnf": "file_config_light",
    "svelte": "file_svelte_light",
    "slim": "file_slim_light",
    "sln": "file_sln_light",
    "rs": "file_rust_light",
    "cs": "file_cs_light",
    "cshtml": "file_cshtml_light",
    "csproj": "file_csproj_light",
    "ex": "file_elixir_light",
    "exs": "file_elixir_light",
    "eex": "file_embedded_elixir_light",
    "heex": "file_embedded_elixir_light",
    "leex": "file_embedded_elixir_light",
    "beam": "file_beam_light",
    "dockerfile": "file_docker_light",
    "swift": "file_swift_light",
    "cljc": "file_clojure_light",
    "cljs": "file_clojure_light",
    "clj": "file_clojure_light",
    "edn": "file_clojure_light",
    "proto": "file_protobuf_light",
    "hcl": "file_hcl_light",
    "rego": "file_rego_light",
    "exe": "file_application_light",
    "ipynb": "file_jupyter_light",
    "mdx": "file_mdx_light",
    "erl": "file_erlang_light",
    "lua": "file_lua_light",
    "hs": "file_haskell_light",
    "graphql": "file_graphql_light",
    "gql": "file_graphql_light",
    "test.ts": "file_test_ts_light",
    "test.tsx": "file_test_tsx_light",
    "test.jsx": "file_test_jsx_light",
    "test.js": "file_test_js_light",
    "db": "file_db_light",
    "sqlite": "file_db_light",
    "sqlite3": "file_db_light",
    "db3": "file_db_light",
    "accdb": "file_db_light",
    "mdb": "file_db_light",
    "dbf": "file_db_light",
    "ndf": "file_db_light",
    "ibd": "file_db_light",
    "frm": "file_db_light",
    "ora": "file_db_light",
    "lock": "file_lock_light",
    "ino": "file_ino_light",
    "jinja": "file_html_light",
    "jinja2": "file_html_light",
    "j2": "file_html_light",
    "html.j2": "file_html_light",
    "razor": "file_cshtml_light",
    "cmake": "file_cmake_light",
    "pdf": "file_pdf_light",
    "gohtml": "file_go_template_light",
    "gotmpl": "file_go_template_light",
    "groovy": "file_groovy_light",
    "bpmn": "file_schema",
    "arb": "file_json_light"
  },
  "BY_NAME": {
    "dune": "file_dune_light",
    "dune-project": "file_dune_light",
    ".gitignore": "file_gitignore_light",
    ".gitattributes": "file_gitignore_light",
    ".gitmodules": "file_gitignore_light",
    ".gitkeep": "file_gitignore_light",
    ".editorconfig": "file_editorconfig_light",
    ".yarnrc": "file_yarn_light",
    "yarn.lock": "file_yarn_light",
    "README": "file_markdown_light",
    ".dockerignore": "file_ignored_light",
    "Dockerfile": "file_docker_light",
    "Dockerfile.dev": "file_docker_light",
    "Dockerfile.test": "file_docker_light",
    "Dockerfile.staging": "file_docker_light",
    "Dockerfile.prod": "file_docker_light",
    "Dockerfile.production": "file_docker_light",
    "Gemfile": "file_gemfile_light",
    "Gemfile.lock": "file_gemfile_light",
    "Makefile": "file_makefile_light",
    ".env": "file_text_light",
    ".env.local": "file_text_light",
    ".env.test": "file_text_light",
    ".env.example": "file_text_light",
    ".env.development": "file_text_light",
    ".env.production": "file_text_light",
    ".env.test.local": "file_text_light",
    ".env.development.local": "file_text_light",
    ".env.production.local": "file_text_light",
    ".env.db": "file_text_light",
    "Cargo.toml": "file_cargo_light",
    "rust-toolchain.toml": "file_cargo_light",
    "Cargo.lock": "file_cargolock_light",
    "CMakeLists.txt": "file_cmake_light",
    "CMakeCache.txt": "file_config_light",
    "pnpm-lock.yaml": "file_pnpm_light",
    "pnpm-workspace.yaml": "file_pnpm_light",
    "tailwind.config.js": "file_tailwind_light",
    "tailwind.config.cjs": "file_tailwind_light",
    "tailwind.config.ts": "file_tailwind_light",
    "vite.config.js": "file_vite_light",
    "vite.config.cjs": "file_vite_light",
    "vite.config.ts": "file_vite_light",
    "postcss.config.js": "file_postcss_light",
    "postcss.config.cjs": "file_postcss_light",
    "postcss.config.ts": "file_postcss_light",
    "angular.json": "file_angular_light",
    ".eslintrc": "file_eslint_light",
    ".eslintrc.cjs": "file_eslint_light",
    ".eslintrc.js": "file_eslint_light",
    ".eslintrc.ts": "file_eslint_light",
    ".eslintrc.json": "file_eslint_light",
    ".eslintrc.yml": "file_eslint_light",
    ".eslintrc.yaml": "file_eslint_light",
    ".eslintignore": "file_eslint_light",
    "go.mod": "file_gomod_light",
    "go.sum": "file_gosum_light",
    "go.work": "file_gowork_light",
    "Directory.Build.props": "file_buildprops_light",
    "main.go": "file_go_run_light",
    "conftest.py": "file_python_tests_light",
    "__init__.py": "file_python_console_light",
    "Jenkinsfile": "file_jenkins"
  },
  "DEFAULT": "file_text_light"
};

const EXT_KEYS_DESC: string[] = [
  "properties",
  "dockerfile",
  "test.tsx",
  "test.jsx",
  "graphql",
  "test.ts",
  "test.js",
  "sqlite3",
  "html.j2",
  "config",
  "svelte",
  "cshtml",
  "csproj",
  "sqlite",
  "jinja2",
  "gohtml",
  "gotmpl",
  "groovy",
  "jsonc",
  "json5",
  "gleam",
  "scala",
  "swift",
  "proto",
  "ipynb",
  "accdb",
  "jinja",
  "razor",
  "cmake",
  "opam",
  "dart",
  "scss",
  "sass",
  "json",
  "html",
  "rake",
  "less",
  "xlsx",
  "webp",
  "jpeg",
  "woff",
  "yaml",
  "java",
  "bash",
  "cxxm",
  "cppm",
  "c++m",
  "toml",
  "http",
  "rest",
  "conf",
  "slim",
  "heex",
  "leex",
  "beam",
  "cljc",
  "cljs",
  "rego",
  "lock",
  "bpmn",
  "mli",
  "css",
  "erb",
  "jsx",
  "tsx",
  "cjs",
  "mjs",
  "cts",
  "mts",
  "csv",
  "xls",
  "vue",
  "png",
  "jpg",
  "gif",
  "ico",
  "svg",
  "ttf",
  "oft",
  "eot",
  "yml",
  "xml",
  "sql",
  "zsh",
  "bat",
  "ps1",
  "hpp",
  "hxx",
  "cpp",
  "cxx",
  "ccm",
  "ixx",
  "cuh",
  "zip",
  "rar",
  "tar",
  "pyi",
  "pyc",
  "php",
  "cfg",
  "cnf",
  "sln",
  "exs",
  "eex",
  "clj",
  "edn",
  "hcl",
  "exe",
  "mdx",
  "erl",
  "lua",
  "gql",
  "db3",
  "mdb",
  "dbf",
  "ndf",
  "ibd",
  "frm",
  "ora",
  "ino",
  "pdf",
  "arb",
  "ml",
  "kt",
  "rb",
  "js",
  "ts",
  "md",
  "sh",
  "hh",
  "cc",
  "cu",
  "gz",
  "7z",
  "py",
  "tf",
  "go",
  "as",
  "rs",
  "cs",
  "ex",
  "hs",
  "db",
  "j2",
  "h",
  "c"
];

export function getJbIconPath(fileName: string, theme: "light" | "dark" = "dark"): string {
  const t = theme === "light" ? LIGHT : DARK;
  const byName = t.BY_NAME[fileName];
  if (byName) return t.ICON_PATHS[byName];
  const lower = fileName.toLowerCase();
  for (const ext of EXT_KEYS_DESC) {
    if (lower.endsWith("." + ext)) {
      const n = t.BY_EXT[ext];
      if (n) return t.ICON_PATHS[n];
    }
  }
  return t.ICON_PATHS[t.DEFAULT];
}
